Reorganize validation modules
mlabs-haskell/orcfax-coop pull request #11
Opened 2024-02-22 09:46 UTC by szg251

In preparation for the offchain component, I reorganized a few things:
- coop-validation renamed to coop-plutus (this module is now responsible for the entire TxInfo building)
- TxInfoBuider module is moved out of the tests folder, so it can be used by other libs

2024-02-23 08:45 UTC, bladyjoker requested changes
Renamings are hard! Good stuff, left some comments.

2024-02-23 08:45 UTC, bladyjoker commented on coop-offchain/Cargo.toml
Please don't use offchain/onchain nomenclature, it doesn't mean anything and it's too vague.

If I'm not mistake this could end up being `coop-txbuilder` as the actual implementation of the TxBuilder gRPC service? We should look into https://github.com/tokio-rs/prost ?

Before this was `coop-pab` which assumes orchestrating queries, transaction building, and calling other services, and providing signatures.

2024-02-23 08:45 UTC, bladyjoker commented on coop-plutus/app/Main.hs
> +parserInfo = info (options <**> helper) (fullDesc <> progDesc "COOP plutus CLI")
I guess capitalize Plutus?

2024-02-23 08:45 UTC, bladyjoker commented on coop-plutus/coop-plutus.cabal
>      Coop.Validation.Location
I suggest you now use:

1. Coop.Plutus.Validation
2. Coop.Plutus.Transactions

?

2024-02-23 08:45 UTC, bladyjoker commented on coop-plutus/src/Coop/TxInfoBuilder/Transactions.hs
So I'd put this in Coop/Plutus/Transactions/<TransactionType>?

This is COOP specific. The other TxInfoBuilder stuff which is generic, I'd keep here where you placed it

2024-02-26 08:27 UTC, szg251 commented on coop-plutus/src/Coop/TxInfoBuilder/Transactions.hs
makes sense, okay

2024-02-27 09:20 UTC, szg251 commented on coop-plutus/app/Main.hs
> +parserInfo = info (options <**> helper) (fullDesc <> progDesc "COOP plutus CLI")
done

2024-02-27 09:20 UTC, szg251 commented on coop-offchain/Cargo.toml
I went with `coop-tx-builder`

2024-03-05 11:54 UTC, closed without merging