Transaction Bakery
mlabs-haskell/orcfax-coop pull request #7
Opened 2024-02-19 11:35 UTC by szg251

- Update lbf
- Move tx-bakery to coop
- Fix fee calculation
- Improve documentation

2024-02-21 14:27 UTC, szg251 commented
I think I will deal with the remaining tasks later after we get e2e testing

2024-02-23 09:19 UTC, bladyjoker requested changes
That's a loooooot! I can't believe you actually managed to push through and submit a transaction! Pretty impressive

2024-02-23 09:19 UTC, bladyjoker commented on tx-bakery/lib/src/lib.rs
> +                    _ => {}
Introduce lib level `errors.rs` and start returning proper errors. Like here, you should throw `errors::TxBuilderError::Internal "Script Purpose <> not supported"

2024-02-23 09:19 UTC, bladyjoker commented on tx-bakery/lib/src/lib.rs
> +            CollateralStrategy::None => {}
What's this about?

2024-02-23 09:19 UTC, bladyjoker commented on tx-bakery/lib/src/lib.rs
> +            }
I don't think any of this should be part of this library. I'd refactor it into `collateral.rs` lib, and this module just expect the collateral stuff to be determined, resolved and supplied.

2024-02-23 09:19 UTC, bladyjoker commented on tx-bakery/lib/src/lib.rs
> +            })
Introduce proper error handling, this looks like it might panic.

2024-02-23 09:19 UTC, bladyjoker commented on tx-bakery/lib/src/lib.rs
> +            .unwrap();
I don't know what `add_change_if_needed` does, but it shouldn't do what the name says. You CAN'T change TxInfo in any circumstance.

2024-02-23 09:19 UTC, bladyjoker commented on tx-bakery/lib/src/submitter.rs
> +    ) -> impl Future<Output = TransactionHash>;
That's not an appropriate method for Submitter, this is pretty much the ONLY thing a Wallet should do.

2024-02-23 09:19 UTC, bladyjoker commented on tx-bakery/lib/src/submitter.rs
> +
Put into Indexer/Query

2024-02-23 09:19 UTC, bladyjoker commented on tx-bakery/lib/src/utils/ogmios.rs
> +    }
Now that I think about it, this should be the method on Submitter

2024-02-23 09:19 UTC, bladyjoker commented on tx-bakery/lib/src/wallet.rs
> +    fn get_change_pkh(&self) -> Ed25519PubKeyHash;
Why change?

2024-02-23 09:19 UTC, bladyjoker commented on tx-bakery/lib/src/wallet.rs
> +    fn get_change_addr(&self) -> Address;
why change?

2024-02-23 09:19 UTC, bladyjoker commented on tx-bakery/tests/validation/tx-bakery-test-scripts.cabal
> +maintainer:    bladyjoker@gmail.com
Dude :D

2024-02-26 08:18 UTC, szg251 commented on tx-bakery/lib/build.nix
> +            pkgs.openssl.dev
This is required by cardano-serialization-lib, I'm not sure if we need to upstream it.
I'm not sure where we can draw a clear line

2024-02-26 08:18 UTC, szg251 commented on tx-bakery/lib/build.nix
> +            pkgs.cargo-nextest
That is true

2024-02-26 08:23 UTC, szg251 commented on tx-bakery/lib/src/lib.rs
> +        let network_id = wallet.get_network_id();
I'm still not sure where to put this, but I was actually following [CIP-30](https://cips.cardano.org/cip/CIP-30/) here.
However, it might not make too much sense, to follow that API

2024-02-26 08:24 UTC, szg251 commented on tx-bakery/lib/src/indexer.rs
> +pub trait Indexer {
Agree

2024-02-26 08:24 UTC, szg251 commented on tx-bakery/lib/src/wallet.rs
> +    fn get_change_pkh(&self) -> Ed25519PubKeyHash;
yeah.... this also comes from CIP-30

2024-02-26 08:25 UTC, szg251 commented on tx-bakery/tests/validation/tx-bakery-test-scripts.cabal
> +maintainer:    bladyjoker@gmail.com
ooooh, I'm putting the blame on you

2024-02-26 10:36 UTC, szg251 commented on tx-bakery/lib/build.nix
> +            pkgs.openssl.dev
I decided to put it there, here's the PR https://github.com/mlabs-haskell/flake-lang.nix/pull/40

2024-02-26 10:37 UTC, szg251 commented on tx-bakery/lib/build.nix
> +            pkgs.cargo-nextest
Also solved in https://github.com/mlabs-haskell/flake-lang.nix/pull/40

2024-03-05 11:52 UTC, merged